import Seo from "../lib/Seo";
import { Eyebrow, Section } from "../components/ui";

const SECTIONS = [
  {
    heading: "1. Acceptance of Terms",
    body: [
      'Welcome to Crowwe. These Terms of Service ("Terms") constitute a legally binding agreement between you and IPI Solutions Nigeria Limited ("we," "us," or "our") governing your access to and use of the Crowwe mobile application, website, and related services (collectively, the "Platform"). By downloading, installing, registering for, or using Crowwe, you agree to be bound by these Terms. If you do not agree to these Terms, you must not use the Platform.',
    ],
  },
  {
    heading: "2. Description of Services",
    body: [
      "Crowwe is a comprehensive digital platform designed to connect individuals and support micro, small, and medium-sized enterprises (MSMEs) across Nigeria and Africa. The Platform's features include, but are not limited to:",
    ],
    bullets: [
      "Social and Communication Tools: Instant messaging, media sharing, and social networking features.",
      "Business Productivity: Digital storefronts, invoicing, receipt generation, and business profile management.",
      "Financial Services: The Crowwe Wallet, enabling peer-to-peer transfers, QR code payments, and business transaction processing.",
      "AI Assistant (Inna): An integrated productivity assistant providing informational support, document drafting, and general organization.",
    ],
  },
  {
    heading: "3. User Accounts and Security",
    body: ["To access most features of the Platform, you must register for an account."],
    bullets: [
      "Eligibility: You must be at least 18 years old to use the financial and business features of the Platform.",
      "Accuracy of Information: You agree to provide current, complete, and accurate information during registration and to update such information as necessary.",
      "Account Security: You are responsible for safeguarding your account credentials and for all activities that occur under your account. You must notify us immediately of any unauthorized use of your account.",
    ],
  },
  {
    heading: "4. Financial Services and Crowwe Wallet",
    body: ["The Crowwe Wallet facilitates digital payments and funds management."],
    bullets: [
      "Regulatory Compliance: Wallet services are provided in compliance with the regulations of the Central Bank of Nigeria (CBN) and other applicable financial authorities.",
      "Transactions: You are responsible for verifying the details of all transactions, including QR code payments and peer-to-peer transfers, before execution.",
      "Fees: Certain transactions may be subject to fees. All applicable fees will be clearly disclosed to you prior to completing a transaction.",
    ],
  },
  {
    heading: "5. AI Assistant (Inna)",
    body: ["Crowwe includes an AI-powered assistant, Inna, designed to aid with productivity, drafting, and business organization."],
    bullets: [
      "Informational Purposes Only: Information provided by the AI assistant does not constitute professional legal, financial, medical, or tax advice.",
      "Verification: You are solely responsible for reviewing, verifying, and editing any documents, contracts, or advice generated by the AI before using them in your business operations.",
    ],
  },
  {
    heading: "6. User Conduct and Acceptable Use",
    body: ["You agree to use the Platform only for lawful purposes. You shall not:"],
    bullets: [
      "Post, transmit, or share any content that is unlawful, harmful, defamatory, obscene, or infringing on intellectual property rights.",
      "Use the Platform to conduct fraudulent activities, money laundering, or any illegal financial transactions.",
      "Attempt to gain unauthorized access to the Platform's systems, disrupt its functionality, or distribute malicious code.",
      "Use automated systems to access the Platform without our express written permission.",
      "Harass, abuse, or harm other users of the Platform.",
    ],
  },
  {
    heading: "7. Intellectual Property",
    body: [],
    bullets: [
      "Our Rights: IPI Solutions Nigeria Limited retains all rights, title, and interest in and to the Platform, including its software, design, logos, and trademarks.",
      "Your Content: You retain ownership of the content you post on the Platform. By posting content, you grant us a non-exclusive, worldwide, royalty-free license to use, display, and distribute your content for the purpose of operating and improving the Platform.",
    ],
  },
  {
    heading: "8. Privacy and Data Protection",
    body: [
      "Your privacy is important to us. Our collection and use of personal information in connection with the Platform is described in our Privacy Policy. By using the Platform, you consent to the collection, use, and sharing of your data as outlined in the Privacy Policy and in accordance with the Nigeria Data Protection Act (NDPA).",
    ],
  },
  {
    heading: "9. Limitation of Liability",
    body: [
      "To the maximum extent permitted by applicable law, IPI Solutions Nigeria Limited shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from:",
    ],
    bullets: [
      "Your access to or use of or inability to access or use the Platform.",
      "Any conduct or content of any third party on the Platform.",
      "Any unauthorized access, use, or alteration of your transmissions or content.",
    ],
  },
  {
    heading: "10. Termination",
    body: [
      "We may suspend or terminate your account and access to the Platform at our sole discretion, without prior notice or liability, for any reason whatsoever, including but not limited to a breach of these Terms. Upon termination, your right to use the Platform will immediately cease.",
    ],
  },
  {
    heading: "11. Governing Law and Dispute Resolution",
    body: [
      "These Terms shall be governed by and construed in accordance with the laws of the Federal Republic of Nigeria, without regard to its conflict of law provisions. Any dispute arising from or relating to these Terms or the Platform shall be resolved through binding arbitration in Abuja, Nigeria, in accordance with the Arbitration and Mediation Act.",
    ],
  },
];

const CONTACT = [
  { label: "Company", value: "IPI Solutions Nigeria Limited" },
  { label: "Address", value: "8 Zambezi Crescent, Maitama, Abuja, Nigeria" },
  { label: "Email", value: "info@ipi.ng" },
  { label: "Phone", value: "08033486748" },
  { label: "Website", value: "www.ipi.ng" },
];

export default function TermsOfService() {
  return (
    <>
      <Seo
        title="Terms of Service"
        description="The terms that govern access to and use of the Crowwe platform, provided by IPI Solutions Nigeria Limited."
        path="/terms"
      />
      <Section style={{ paddingTop: 56, maxWidth: 760 }}>
        <Eyebrow>Legal</Eyebrow>
        <h1 style={{ fontSize: 32, fontWeight: 800, color: "var(--dark)", letterSpacing: "-0.01em", marginBottom: 8 }}>
          Terms of Service
        </h1>
        <p style={{ fontSize: 13.5, color: "var(--faint)", marginBottom: 32 }}>Effective Date: 28 August 2026</p>

        {SECTIONS.map((s) => (
          <div key={s.heading} style={{ marginBottom: 32 }}>
            <h2 style={{ fontSize: 18, fontWeight: 800, color: "var(--dark)", marginBottom: 10 }}>{s.heading}</h2>
            {s.body.map((p, i) => (
              <p key={i} style={{ fontSize: 15, color: "var(--muted)", lineHeight: 1.7, marginBottom: s.bullets ? 12 : 0 }}>
                {p}
              </p>
            ))}
            {s.bullets && (
              <ul style={{ margin: 0, paddingLeft: 20 }}>
                {s.bullets.map((b, i) => (
                  <li key={i} style={{ fontSize: 15, color: "var(--muted)", lineHeight: 1.7, marginBottom: 8 }}>
                    {b}
                  </li>
                ))}
              </ul>
            )}
          </div>
        ))}

        <div style={{ marginBottom: 8 }}>
          <h2 style={{ fontSize: 18, fontWeight: 800, color: "var(--dark)", marginBottom: 10 }}>
            12. Contact Information
          </h2>
          <p style={{ fontSize: 15, color: "var(--muted)", lineHeight: 1.7, marginBottom: 12 }}>
            If you have any questions about these Terms, please contact us at:
          </p>
          <div className="card-flat">
            {CONTACT.map((c) => (
              <div key={c.label} style={{ display: "flex", gap: 8, fontSize: 14.5, marginBottom: 6 }}>
                <span style={{ fontWeight: 700, color: "var(--ink)", minWidth: 80 }}>{c.label}:</span>
                <span style={{ color: "var(--muted)" }}>{c.value}</span>
              </div>
            ))}
          </div>
        </div>
      </Section>
    </>
  );
}